baseurl = "http://www.tengio.com/"
languageCode = "en-us"
title = "Tengio Limited"
theme = "hugo-creative-theme"

[params]
	name = "Luigi Agosti, Akshay Dashrath"
	description = "Developers rule"

	[params.navigation]
		brand = "small_logo.png"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			values  = "Values"
			portfolio = "Portfolio"
			contact   = "Contact"

	[params.hero]
		slogan     = ""
		subtitle   = ""

	[params.about]
		headline    = "About us"
		description = "We are mobile native developer experts"
		buttonText  = "Get started!"

		[[params.about.list]]
			 name = "Akshay Dashrath"
			 bio  = "Boldness and disruption"
			 image = "1.jpg"

    [[params.about.list]]
			name = "Luigi Agosti"
			bio  = "Consistency and experience"
			image = "luigi.png"

		[[params.about.list]]
			name = "Florent Guillemot"
			bio  = "Ginuous and passion"
			image = "3.jpg"

		[[params.about.list]]
			name = "Francesco Costarelli"
			bio  = "Sleeping apprentice"
			image = "4.jpg"

		[[params.about.list]]
			name = "Ozhan Saat"
			bio  = "Jumping apprentice"
			image = "5.jpg"

		[params.values]
			headline = "Our values"

			[[params.values.list]]
				 icon = "fa-diamond"
				 title = "Code Quality"
				 description = "We write code that we are happy to maintain and grow."

			[[params.values.list]]
				 icon = "fa-rocket"
				 title = "Speed"
				 description = "We deliver at an amazing speed."

			[[params.values.list]]
				 icon = "fa-comments-o"
				 title = "Comunication"
				 description = "We see our clients are parteners in the project success."

			[[params.values.list]]
				 icon = "fa-heart"
				 title = "Passion"
				 description = "We build software because that what we love."

  [params.services]
		headline = "Our services"

    [[params.services.list]]
       title = "Application Development"
       description = "We provide end to end development of your Mobile Application on Android or iOS."

    [[params.services.list]]
       title = "UX Design and Longevity"
       description = "We handle UX Design requirements and provide advice to ensure that your Apps are future proof and ready to be featured on respective App Stores."

		[[params.services.list]]
       title = "Support Contracts"
       description = "We specialise in providing long term support to your Apps with our competitive support and handover contracts."

    [[params.services.list]]
       title = "Recruitment and Training"
       description = "We're glad to help you setup and recruit internal teams, and train them to get up to speed with the codebase as well as platform best practices."

	  [[params.services.list]]
       title = "Legacy Codebases"
       description = "We specialise in maintainence as well as reworking of legacy codebases."

	 	[[params.services.list]]
       title = "Strategy Analysis and Training"
       description = "We will help you determine long term mobile strategy, focusing on growth and revenue. We also provide training in Android and iOS."

	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

	[params.aside]
		headline = ""


	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "+44 (0) 7816863557"
		email = "contact@tengio.com"
		address = "35 Kingsland Road Shoreditch E2 8AA"
		city = "London"
		country = "United Kingdom"
		twitter = "http://www.twitter.com/tengioltd"
		companyName = "Tengio Ltd"
