application: tengio-web
version: 11
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: img/small_logo.png
  upload: img/small_logo.png

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /font-awesome
  static_dir: font-awesome

- url: /css
  static_dir: css

- url: /404
  static_dir: 404

- url: /blog
  static_files: blog/index.html
  upload: blog/index.html

- url: /blog/
  static_files: blog/index.html
  upload: blog/index.html

- url: /tags
  static_files: tags/index.html
  upload: tags/index.html

- url: /tags/
  static_files: tags/index.html
  upload: tags/index.html

- url: /blog/(.+)/
  static_files: blog/\1/index.html
  upload: blog/(.+)/index.html

- url: /tags/(.+)/
  static_files: tags/\1/index.html
  upload: tags/(.+)/index.html

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /humans.txt
  static_files: humans.txt
  upload: humans.txt

- url: /.*
  static_files: index.html
  upload: index.html
